{{- if .Values.imageCredentials.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "radon.imagePullSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "radon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{template "imagePullSecretPrivate" .}}
{{- end }}
